<?php

/** API version: 7d364c51-04c7-45e3-af61-f82423bcc39c */

namespace MercadoPago\Resources\Order;

use MercadoPago\Serialization\Mapper;

/**
 * Represents the payment method details for an order payment or attempt.
 *
 * Contains all method-specific data such as card tokens, boleto barcodes,
 * Pix QR codes, installment counts, and 3DS security information.
 *
 * @see \MercadoPago\Resources\Order\Payment
 * @see \MercadoPago\Resources\Order\Attempt
 */
class PaymentMethod
{
    /** Class mapper. */
    use Mapper;

    /** Payment method identifier (e.g., "visa", "pix", "bolbradesco"). */
    public ?string $id;

    /** Payment method type (e.g., "credit_card", "debit_card", "bank_transfer", "ticket"). */
    public ?string $type;

    /** Saved card identifier when using a stored card-on-file. */
    public ?string $card_id;

    /** Tokenized card data generated by the MercadoPago.js SDK. */
    public ?string $token;

    /** Number of installments selected by the buyer. */
    public ?int $installments;

    /** Text that appears on the buyer's card statement for this charge. */
    public ?string $statement_descriptor;

    /** URL of the printable payment ticket (boleto/lottery). */
    public ?string $ticket_url;

    /** Barcode content string for boleto or lottery-type payments. */
    public ?string $barcode_content;

    /** Payment reference code displayed to the buyer for off-line payments. */
    public ?string $reference;

    /** External reference identifier for the payment method. */
    public ?string $reference_id;

    /** Verification code for bank transfer or wallet payments. */
    public ?string $verification_code;

    /** Financial institution code processing the payment (e.g., bank code for PSE). */
    public ?string $financial_institution;

    /** Pix QR code string for copy-and-paste payments. */
    public ?string $qr_code;

    /** Base64-encoded Pix QR code image. */
    public ?string $qr_code_base64;

    /** Digitable line for boleto payments (numeric barcode representation). */
    public ?string $digitable_line;

    /** End-to-end transaction identifier for Pix payments. */
    public ?string $e2e_id;

    /** URL to redirect the buyer for external payment authorization (e.g., bank redirect). */
    public ?string $redirect_url;

    /** 3D Secure and other transaction security details. Maps to {@see TransactionSecurity}. */
    public array|object|null $transaction_security;

    private $map = [
        "transaction_security" => "MercadoPago\Resources\Order\TransactionSecurity",
    ];

    /**
     * Method responsible for getting map of entities.
     */
    public function getMap(): array
    {
        return $this->map;
    }
}
